// ============================================================
// SHAFFERS ABROAD — content file (single source of truth on the site)
// Mirrors the master dossier in this repo (./trip-dossier.md) and in iCloud Drive.
// Edit here, then commit + push.
// ============================================================

window.TRIP = {
  meta: {
    title: "Shaffers Abroad",
    tagline: "Our two weeks across Morocco, the Mediterranean, and France",
    departDate: "2026-05-23",  // drive to Dallas (pre-trip night)
    sailDate: "2026-05-26",
    returnDate: "2026-06-05",
    travelers: "Jason & Rachel",
    hashtag: "ShaffersAbroad26",
  },

  // Lookup of coordinates per day (used for weather + map). lat/lng pairs.
  // Day by day. Day 0 is the pre-trip Dallas overnight.
  days: [
    {
      id: "day-0",
      date: "2026-05-23",
      label: "Sat May 23 · Night before",
      city: "Dallas, TX",
      country: "USA",
      flag: "🇺🇸",
      kicker: "Drive to Dallas",
      title: "Bags in the car, Dallas tonight.",
      summary: "Drive to Dallas, dinner at Culver's, then check in at The Highland. Out for sack lunches for the kids' camp trip. Two rooms for a quiet night before the trip.",
      photos: [],
      audio: null,
      journal: "Smooth drive east on I-20 — minimal construction for once. Dinner at Culver's before checking in. After we settled in at the Highland, we went out for sack lunches for the kids' camp trip tomorrow. Separate rooms for the kids tonight so the four of us could try for a quiet night.",
      plan: [
        { time: "Morning",       text: "Drive east from Midland to Dallas." },
        { time: "Evening",       text: "Dinner at Culver's." },
        { time: "After dinner",  text: "Check in at The Highland Dallas (5300 E Mockingbird Ln)." },
        { time: "After check-in", text: "Out to pick up sack lunches for the kids' camp trip tomorrow." },
        { time: "Night",         text: "Two rooms. Early to bed." },
      ],
      smallFind: {
        number: "01",
        label: "Blue tile shower wall, The Highland",
        text: "Rachel liked the blue tile in the shower."
      },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [
        { place: "Culver's", dish: "dinner before checking in", when: "dinner", cost: "" },
      ],
    },
    {
      id: "day-1",
      date: "2026-05-24",
      label: "Day 1 · Sun May 24",
      city: "DFW → JFK → Casablanca",
      country: "🇺🇸 → 🇲🇦",
      flag: "✈️",
      kicker: "Travel day · the long one",
      title: "Wheels up, two planes, one ocean.",
      summary: "Up early. Drop the kids at Lake Highlands High to catch the camp bus, then over to DFW. Park at Terminal A, TerminaLink bus to Terminal C for check-in. AA to JFK at 11:57 AM, then the overnight Royal Air Maroc 787 to Casablanca.",
      photos: [],
      audio: null,
      journal: "Spent the time between check-in and the flight in the Admirals Club lounge. Breakfast: bao buns stuffed with scrambled eggs and bacon. Delicious.",
      plan: [
        { time: "Early AM",       text: "Drop the kids at Lake Highlands High for the camp bus." },
        { time: "~9:00 AM",       text: "Park at DFW Terminal A garage. TerminaLink bus over to Terminal C for AA check-in, bag drop, and security." },
        { time: "Pre-flight",     text: "Admirals Club lounge. Breakfast — bao buns stuffed with scrambled eggs and bacon." },
        { time: "11:57 AM",       text: "AA 1049 DFW → JFK." },
        { time: "4:38 PM",        text: "Land JFK Terminal 8 — about a 4-hour layover for the international transfer." },
        { time: "8:45 PM",        text: "AA 7951 / Royal Air Maroc 787 JFK → Casablanca (overnight)." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [
        { place: "Admirals Club, DFW", dish: "bao buns stuffed with scrambled eggs and bacon", when: "breakfast", cost: "" },
      ],
    },
    {
      id: "day-2",
      date: "2026-05-25",
      label: "Day 2 · Mon May 25",
      city: "Casablanca",
      country: "Morocco",
      flag: "🇲🇦",
      kicker: "Land in Africa",
      title: "Mint tea in the Habous Quarter.",
      summary: "Arrive 8:50 AM. Nap at the Marriott, then a self-guided afternoon in the Habous Quarter — leather, lanterns, spices, a slow tea, dinner back at the hotel. Eid al-Adha is two days off, so the city feels busy and warm.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Morocco's largest city and commercial heart, sat right on the Atlantic. The Casablanca most Americans picture comes from the 1942 film — but the real city is Art Deco boulevards, French colonial buildings, a working port, and over four million people. The Habous Quarter, where we'll spend the afternoon, is a 1920s 'new medina' built by the French to look traditional — neat, walkable, full of leather and lantern shops.",
        timing: "Two days before Eid al-Adha (Feast of Sacrifice — May 27 this year). The city will feel busy in a particular way: sheep being sold on corners, families traveling, restaurants and markets in pre-holiday motion. Atmospheric, not chaotic.",
        tidbit: "The Hassan II Mosque sits partly out over the Atlantic — its 690-ft minaret is among the tallest in the world, and the floor of the prayer hall has glass panels looking down to the sea below."
      },
      plan: [
        { time: "8:50 AM",  text: "Land at Casablanca (CMN)." },
        { time: "~10:15 AM", text: "Taxi from the RAM official stand to the Marriott — drop bags, nap." },
        { time: "Late AM",  text: "Light brunch at the hotel." },
        { time: "2:00 PM",  text: "Red petit taxi from the Marriott to the Habous Quarter." },
        { time: "2:30–5:00 PM", text: "Habous Quarter wander — mint tea, leather and spice and lantern shops." },
        { time: "5:30 PM",  text: "Taxi back to the Marriott." },
        { time: "Evening",  text: "Dinner. Early to bed — flight to Málaga in the morning." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-3",
      date: "2026-05-26",
      label: "Day 3 · Tue May 26",
      city: "Casablanca → Málaga · Embark",
      country: "Morocco → Spain",
      flag: "🛳",
      kicker: "Board the MSC Opera",
      title: "Crossing to Spain — boarding day.",
      summary: "Morning Royal Air Maroc to Málaga. Taxi to the cruise terminal. Onboard the MSC Opera by 4 PM, sailing 6 PM. Eight nights, six ports.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Málaga is the gateway to Spain's Costa del Sol — Mediterranean light, beach culture, palm-lined plazas. It's also one of the oldest continuously inhabited cities in Europe, founded by Phoenician sailors around 770 BC.",
        tidbit: "Pablo Picasso was born here in 1881. His childhood home on the Plaza de la Merced is now a small museum."
      },
      plan: [
        { time: "6:00 AM",  text: "Wake. Out of the Marriott by 7:00." },
        { time: "7:35 AM",  text: "Arrive Casablanca airport (RAM recommends 4 hours early). Check-in closes 10:05, gate closes 10:50." },
        { time: "11:05 AM", text: "AT 988 Royal Air Maroc CMN → Málaga (AGP). Lands 13:20." },
        { time: "~2:15 PM", text: "Customs, bags, taxi to the Málaga cruise terminal (Dique de Levante)." },
        { time: "4:00 PM",  text: "Cruise check-in deadline — onboard the MSC Opera." },
        { time: "6:00 PM",  text: "Ship sails. Eight nights, six ports." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-4",
      date: "2026-05-27",
      label: "Day 4 · Wed May 27",
      city: "Cádiz · Seville",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 1",
      title: "Savoury Seville on foot.",
      summary: "Dock in Cádiz 7 AM. MSC excursion takes us to Seville for a walking tour — cathedral, orange-tree courtyards, the old Jewish quarter. Back onboard by 5 PM.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Cádiz claims to be the oldest continuously inhabited city in western Europe — Phoenicians founded it around 1100 BC. It's where Columbus set sail on his second and fourth voyages. The MSC excursion takes us inland to Seville, the Andalusian capital — flamenco, orange-blossom courtyards, the Real Alcázar palace, and Columbus's tomb.",
        timing: "Eid al-Adha — Morocco celebrates today. The boat will feel the shift as the cruise moves fully into Spanish waters.",
        tidbit: "Seville Cathedral holds the largest Gothic interior in the world. Its bell tower, the Giralda, was originally a 12th-century minaret — they kept the Moorish base and just stacked a Renaissance belfry on top."
      },
      plan: [
        { time: "7:00 AM",  text: "Dock in Cádiz." },
        { time: "Morning",  text: "MSC excursion CAD11 — bus to Seville for a walking tour: cathedral, orange-tree courtyards, the old Jewish quarter." },
        { time: "Lunch",    text: "Lunch in Seville (part of the tour or on our own depending on the operator)." },
        { time: "Afternoon", text: "Return drive to Cádiz." },
        { time: "5:00 PM",  text: "Back aboard. Ship sails for Lisbon." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-5",
      date: "2026-05-28",
      label: "Day 5 · Thu May 28",
      city: "Lisbon",
      country: "Portugal",
      flag: "🇵🇹",
      kicker: "Cruise · Port 2",
      title: "Pastel de nata, then the city on foot.",
      summary: "Morning pastel-de-nata masterclass at Nat'elier (10 AM). Afternoon walk down through Santa Justa Lift, the Carmo Convent, Time Out Market for lunch, the river at Praça do Comércio.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Portugal's coastal capital, built on seven hills above the Tagus River. Lisbon launched the Age of Discovery in the 1400s — Vasco da Gama sailed from here to India. Pastel de nata (the custard tart) was invented by Hieronymite monks at the Belém Monastery before 1820, when the original recipe leaked to a local bakery that still makes them today.",
        tidbit: "The 1755 earthquake — one of the deadliest in human history — destroyed most of the city in minutes. The grid you'll walk in the Baixa downtown was rebuilt from scratch by the Marquês de Pombal in one of Europe's earliest urban-planning interventions."
      },
      plan: [
        { time: "9:00 AM",  text: "Dock in Lisbon." },
        { time: "9:50 AM",  text: "Arrive at Nat'elier (Rua de Santa Justa 87)." },
        { time: "10:00 AM", text: "Pastel de Nata Masterclass — two hours, ends with a bag of warm tarts." },
        { time: "Midday",   text: "Lunch in town. (Time Out Market is one option, the chef-curated food hall in the Mercado da Ribeira.)" },
        { time: "Afternoon", text: "Self-guided walk: Santa Justa Lift → Carmo Convent → Praça do Comércio + Cais das Colunas → Sé Cathedral → Miradouro de Santa Luzia." },
        { time: "4:30 PM",  text: "Back aboard." },
        { time: "6:00 PM",  text: "Ship sails." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-6",
      date: "2026-05-29",
      label: "Day 6 · Fri May 29",
      city: "At Sea",
      country: "Mediterranean",
      flag: "🌊",
      kicker: "Cruise · Sea day",
      title: "A day for the deck chairs.",
      summary: "Heading east into the Med. Books, coffee, sun, an espresso, a long lunch. Repeat.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "A full day at sea, crossing east from the Atlantic side of Iberia into the Mediterranean proper.",
        tidbit: "The Mediterranean is about 2.5 million square kilometers — roughly 1% of the world's ocean area, but the largest inland sea on the planet. Average depth: about a mile."
      },
      plan: [
        { time: "All day",  text: "Nothing scheduled. Deck chairs, books, espresso, a long lunch, the pool, the ship." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-7",
      date: "2026-05-30",
      label: "Day 7 · Sat May 30",
      city: "Alicante · Guadalest",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 3",
      title: "Spanish castle magic in the mountains.",
      summary: "Dock 9 AM. Bus up into the Costa Blanca hills to Guadalest, a tiny clifftop village in a Moorish castle. Back by mid-afternoon.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Alicante is a Costa Blanca port city below the Castillo de Santa Bárbara, a Moorish hilltop fortress. The MSC excursion goes inland to Guadalest — a fortified clifftop village built into a 595-meter mountain pass. Population about 210. Held by the Moors, then taken by the Crown of Aragon in 1308 and held by the same noble family for the next five centuries.",
        tidbit: "Guadalest's church and bell tower had to be carved straight out of the solid rock of the cliff — the only way to fit a town up there."
      },
      plan: [
        { time: "9:00 AM",  text: "Dock in Alicante." },
        { time: "Morning",  text: "MSC excursion ALI11 — bus up into the Costa Blanca hills to Guadalest. Castle, village, the views." },
        { time: "~2:00 PM", text: "Return drive to Alicante. Optional time on the esplanade if there's any left." },
        { time: "5:00 PM",  text: "Back aboard. Ship sails." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-8",
      date: "2026-05-31",
      label: "Day 8 · Sun May 31",
      city: "Mahón, Menorca",
      country: "Spain · Balearics",
      flag: "🇪🇸",
      kicker: "Cruise · Port 4 · Free day",
      title: "The quiet Balearic.",
      summary: "Quieter sister to Mallorca and Ibiza. Mahón has one of the deepest natural harbors in the world. A wander, a long lunch, gin and lemonade on a terrace.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "The capital of Menorca, the quietest of the Balearic Islands. Mahón has the second-deepest natural harbor in the world — only Pearl Harbor is deeper. Britain held Menorca for most of the 18th century, and you can still see the influence in the architecture and the local fondness for gin.",
        tidbit: "The word 'mayonnaise' comes from Mahón. It was invented here by a French chef during the British siege of 1756 — originally 'Mahonnaise.'"
      },
      plan: [
        { time: "9:00 AM",  text: "Dock in Mahón." },
        { time: "Day",      text: "Free day — no excursion booked. A wander into town, a long lunch on a terrace, gin and lemonade (the local specialty: pomada)." },
        { time: "4:00 PM",  text: "Back aboard. Ship sails for Sardinia." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-9",
      date: "2026-06-01",
      label: "Day 9 · Mon Jun 1",
      city: "Olbia, Sardinia · La Maddalena",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 5",
      title: "Boating the La Maddalena Archipelago.",
      summary: "Dock 10 AM. Out on the water through the granite islands of La Maddalena — pale-turquoise coves, beach stops, the kind of color that doesn't photograph right.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Olbia is the gateway to Sardinia's Costa Smeralda — the emerald-water coast. The La Maddalena Archipelago is a national park of seven granite islands off the northeast tip, famous for water in shades of blue you don't quite believe.",
        tidbit: "Giuseppe Garibaldi, the soldier-statesman who unified Italy, spent his final years on Caprera, one of the La Maddalena islands. His house is now a museum — he chose it specifically because it was about as far as one could get from politics."
      },
      plan: [
        { time: "10:00 AM", text: "Dock in Olbia." },
        { time: "Morning",  text: "MSC excursion OLB01 — boat tour through the La Maddalena Archipelago. Beach stops, swim breaks, the granite-and-turquoise coastline." },
        { time: "Afternoon", text: "Continued boat tour and return to port." },
        { time: "7:00 PM",  text: "Back aboard. Ship sails for Genoa." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-10",
      date: "2026-06-02",
      label: "Day 10 · Tue Jun 2",
      city: "Genoa",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 6 · Free day",
      title: "The old maritime republic.",
      summary: "Narrow medieval lanes, painted palazzos, the smell of focaccia. The birthplace of Columbus and pesto. The Italian Riviera at our backs.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "One of Europe's great old maritime republics — Genoa rivaled Venice for centuries. Christopher Columbus was born here. The Banca di San Giorgio, founded here in 1407, was one of the first chartered banks in the world. The 16th-century Strada Nuova — a street of palaces built by the city's noble families — is a UNESCO site.",
        tidbit: "Both focaccia and pesto were invented in Genoa. The classical pesto recipe insists on Genoese basil only — DOP-protected and grown in greenhouses on the city's western slopes."
      },
      plan: [
        { time: "9:00 AM",  text: "Dock in Genoa." },
        { time: "Day",      text: "Free day — no excursion booked. The medieval old town, the Strada Nuova palaces, focaccia and pesto, a walk by the old port." },
        { time: "6:00 PM",  text: "Back aboard. Ship sails for Marseille — the final leg." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-11",
      date: "2026-06-03",
      label: "Day 11 · Wed Jun 3",
      city: "Marseille → Paris",
      country: "France",
      flag: "🇫🇷",
      kicker: "Disembark · Onward",
      title: "Off the ship and on to Paris.",
      summary: "Disembark Marseille 9 AM. Afternoon flight to Paris. Check in at Le Méridien Arc de Triomphe, dinner, sleep.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Marseille is France's oldest city, founded by Greek sailors around 600 BC. France's largest port — gritty, Mediterranean, multicultural — closer in feel to Naples than to Paris. Then a short flight north to Paris, the capital on the Seine.",
        tidbit: "The French national anthem, 'La Marseillaise,' was actually composed in Strasbourg but adopted by volunteers from Marseille who sang it as they marched on Paris during the 1792 Revolution. The name stuck."
      },
      plan: [
        { time: "9:00 AM",  text: "Disembark MSC Opera in Marseille." },
        { time: "Midday",   text: "Cruise transfer or taxi to Marseille airport. Check-in deadline 14:35." },
        { time: "3:05 PM",  text: "AF 7339 Marseille → Paris CDG. Lands 16:35." },
        { time: "Late PM",  text: "Le Bus Direct (or taxi) into Paris. Check in at Le Méridien Étoile (Arc de Triomphe)." },
        { time: "Evening",  text: "Dinner. Early to bed — Normandy starts at 7 AM tomorrow." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-12",
      date: "2026-06-04",
      label: "Day 12 · Thu Jun 4",
      city: "Normandy + Mont Saint-Michel",
      country: "France",
      flag: "🇫🇷",
      kicker: "Day trip · 7 AM start",
      title: "D-Day beaches and a fortress on the bay.",
      summary: "Full-day Amigo Tours private trip — Omaha Beach, the American Cemetery, then the impossible silhouette of Mont Saint-Michel rising from the tide.",
      photos: [],
      audio: null,
      journal: "",
      context: {
        about: "Two icons in a single long day. Normandy's beaches — Omaha, Utah, Gold, Juno, Sword — were the site of the Allied landings on June 6, 1944, the start of the liberation of western Europe. The American Cemetery at Colleville-sur-Mer overlooks Omaha Beach. Then west to Mont Saint-Michel, a medieval abbey on a tidal island rising from the bay — UNESCO since 1979, monastic since the 8th century.",
        timing: "Two days before the 82nd anniversary of D-Day (June 6, 1944). Memorial events, gatherings, and ceremonies will be ramping up across the beaches and in the cemeteries as we visit. Veterans and families come back every year — fewer of the original Allied soldiers left each anniversary.",
        tidbit: "At Mont Saint-Michel the tide retreats up to 14 km out into the bay — one of the largest tidal ranges in Europe — and can rush back in at the speed of a galloping horse. Medieval pilgrims occasionally drowned trying to cross at the wrong hour."
      },
      plan: [
        { time: "7:00 AM",  text: "Meet the Amigo Tours van at 11 Bd Pershing — in front of the Hyatt Regency Étoile. About a 5-minute walk from Le Méridien." },
        { time: "Morning",  text: "Drive to Normandy. Omaha Beach. The American Cemetery at Colleville-sur-Mer." },
        { time: "Midday",   text: "Drive west to Mont Saint-Michel." },
        { time: "Afternoon", text: "Visit Mont Saint-Michel — the abbey, the village built up the rock, the bay." },
        { time: "Evening",  text: "Drive back to Paris. Late dinner." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
    {
      id: "day-13",
      date: "2026-06-05",
      label: "Day 13 · Fri Jun 5",
      city: "Paris → Home",
      country: "France → USA",
      flag: "🇺🇸",
      kicker: "Travel day",
      title: "Home to Texas.",
      summary: "One last espresso. AA 49 nonstop Paris → DFW, lands 1:30 PM. Tired, full, and happy.",
      photos: [],
      audio: null,
      journal: "",
      plan: [
        { time: "Morning",  text: "Out of Le Méridien. Le Bus Direct or taxi to CDG." },
        { time: "10:00 AM", text: "AA 49 CDG → DFW. Lands 1:30 PM." },
        { time: "Afternoon", text: "Customs at Terminal D. TerminaLink shuttle to Terminal A garage. Drive home." },
      ],
      smallFind: { number: "", label: "", text: "", photo: "" },
      postcardTo: { to: "", text: "", signoff: "" },
      meals: [],
    },
  ],

  // Coordinates per day (latitude, longitude) — used for weather + map pins.
  // For travel days, use the destination city. For sea days, use a mid-ocean pin.
  coords: {
    "day-0":  { lat: 32.78, lng: -96.80, where: "Dallas, TX" },
    "day-1":  { lat: 33.57, lng:  -7.59, where: "Casablanca, MA" },
    "day-2":  { lat: 33.57, lng:  -7.59, where: "Casablanca, MA" },
    "day-3":  { lat: 36.72, lng:  -4.42, where: "Málaga, ES" },
    "day-4":  { lat: 36.53, lng:  -6.30, where: "Cádiz, ES" },
    "day-5":  { lat: 38.72, lng:  -9.14, where: "Lisbon, PT" },
    "day-6":  { lat: 36.50, lng:  -3.00, where: "Mediterranean Sea" },
    "day-7":  { lat: 38.35, lng:  -0.48, where: "Alicante, ES" },
    "day-8":  { lat: 39.89, lng:   4.27, where: "Mahón, Menorca" },
    "day-9":  { lat: 40.92, lng:   9.50, where: "Olbia, IT" },
    "day-10": { lat: 44.41, lng:   8.93, where: "Genoa, IT" },
    "day-11": { lat: 48.86, lng:   2.35, where: "Paris, FR" },
    "day-12": { lat: 49.28, lng:  -0.70, where: "Bayeux / Normandy, FR" },
    "day-13": { lat: 48.86, lng:   2.35, where: "Paris → DFW" },
  },

  // Back of the book — reflections after the trip. Populated when you're home.
  backOfBook: {
    whereWeSlept: [
      // { place: "The Highland", city: "Dallas", nights: 1, verdict: "" },
      // { place: "Casablanca Marriott", city: "Casablanca", nights: 1, verdict: "" },
      // { place: "MSC Opera, cabin 8208", city: "at sea", nights: 8, verdict: "" },
      // { place: "Le Méridien Étoile", city: "Paris", nights: 2, verdict: "" },
    ],
    wedDoAgain: [
      // "Pastel de nata masterclass — short, fun, ended with a bag of warm pastries",
    ],
    wedSkip: [
      // "...",
    ],
    wishWedBrought: [
      // "A second pair of walking shoes",
    ],
    learned: [
      // Words, phrases, signs that stuck with us.
      // { word: "saudade", from: "Portugal", meaning: "a wistful longing for what's gone" },
    ],
  },

  cities: [
    { name: "Dallas", flag: "🇺🇸" },
    { name: "Casablanca", flag: "🇲🇦" },
    { name: "Málaga", flag: "🇪🇸" },
    { name: "Cádiz · Seville", flag: "🇪🇸" },
    { name: "Lisbon", flag: "🇵🇹" },
    { name: "Alicante", flag: "🇪🇸" },
    { name: "Mahón", flag: "🇪🇸" },
    { name: "Olbia · Sardinia", flag: "🇮🇹" },
    { name: "Genoa", flag: "🇮🇹" },
    { name: "Marseille", flag: "🇫🇷" },
    { name: "Paris", flag: "🇫🇷" },
    { name: "Normandy", flag: "🇫🇷" },
  ],

  whereNow: {
    city: "Midland, TX",
    country: "Pre-trip · home",
    note: "Bags by the door. Final check.",
    updated: "2026-05-22",
  },

  // ============================================================
  // PRIVATE — behind the password on /private.html.
  // ============================================================
  private: {
    flights: [
      {
        date: "Sun May 24",
        route: "DFW (Term C) → JFK (Term 8)",
        airline: "American AA 1049 · Airbus A321",
        times: "11:57 AM → 4:38 PM",
        seats: "Jason 14F · Rachel 14E (Economy L)",
        confirmation: "ECWYBK",
      },
      {
        date: "Sun May 24",
        route: "JFK → CMN (Casablanca)",
        airline: "American AA 7951 / Royal Air Maroc · Boeing 787-9",
        times: "8:45 PM → 8:50 AM May 25 (overnight)",
        seats: "Economy L",
        confirmation: "CW9X3L (RAM) · ECWYBK (AA)",
      },
      {
        date: "Tue May 26",
        route: "CMN (Term 1) → AGP (Málaga)",
        airline: "Royal Air Maroc AT 988 · 737 MAX 8",
        times: "11:05 → 13:20 (1h 15m)",
        seats: "Jason 9B · Rachel 9A",
        confirmation: "Y7JINE · eTickets: J 1472426730054, R 1472426730055",
      },
      {
        date: "Wed Jun 3",
        route: "MRS (Term 1) → CDG (Term 2F)",
        airline: "Air France AF 7339",
        times: "15:05 → 16:35 (1h 30m)",
        seats: "Jason 6B · Rachel 6A",
        confirmation: "YJPQJY · check-in deadline 14:35",
      },
      {
        date: "Fri Jun 5",
        route: "CDG → DFW",
        airline: "American AA 49 · Boeing 787-9",
        times: "10:00 AM → 1:30 PM",
        seats: "29D · 29E (Economy O)",
        confirmation: "ECWYBK (round-trip ref)",
      },
    ],

    hotels: [
      {
        date: "May 23 (1 night) · Pre-trip",
        name: "The Highland Dallas (Curio / Hilton)",
        city: "5300 E Mockingbird Ln, Dallas TX 75206",
        phone: "+1 214-520-7969",
        confirmation: "3482144721",
        notes: "1 King Luxury · check-in 3 PM · check-out 12 PM · Hilton Honors #552163196 · valet $55/night",
      },
      {
        date: "May 25 (1 night)",
        name: "Casablanca Marriott Hotel",
        city: "100 Avenue des FAR, Casablanca 20000",
        phone: "+212-522-439494",
        confirmation: "74156980",
        notes: "Superior King, city view · check-in 3 PM, check-out 12 PM · prepaid · Bonvoy Platinum · ⚠ confirm Rachel is on the booking (shows '1 Adult')",
      },
      {
        date: "Jun 3–4 (2 nights)",
        name: "Le Méridien Paris Arc de Triomphe",
        city: "81 Bd Gouvion Saint-Cyr, Paris 75017",
        phone: "+33-1-40683434",
        confirmation: "84262397",
        notes: "Executive King · check-in 4 PM, check-out 12 PM · prepaid · Bonvoy Platinum · refurbishment underway (full service)",
      },
    ],

    cruise: {
      ship: "MSC Opera",
      booking: "71516081",
      checkIn: "Completed (eTicket received Apr 25)",
      boardDate: "Tue May 26 · Málaga Cruise Terminal (Dique de Levante) · board 12–4 PM, sail 6 PM",
      disembarkDate: "Wed Jun 3 · Marseille · 9 AM",
      duration: "8 nights · 6 ports",
      stateroom: "Cabin 8208 · Deck 8 · Outside (window) · Fantastica",
      diningTime: "First Seating (table assigned on board)",
      assembly: "Station J",
      guestIds: "Jason 182730562 · Rachel 182730563",
      wifi: "Browse Wi-Fi package, 2 devices on Jason's account · network: MSCHOTSPOT",
      app: "MSC for Me · log in with booking #71516081",
      portTimes: [
        "Tue May 26 · Málaga · embark 12–4 PM, sail 6 PM",
        "Wed May 27 · Cádiz · 7 AM – 5 PM",
        "Thu May 28 · Lisbon · 9 AM – 6 PM",
        "Fri May 29 · At Sea",
        "Sat May 30 · Alicante · 9 AM – 5 PM",
        "Sun May 31 · Mahón, Menorca · 9 AM – 4 PM",
        "Mon Jun 1 · Olbia, Sardinia · 10 AM – 7 PM",
        "Tue Jun 2 · Genoa · 9 AM – 6 PM",
        "Wed Jun 3 · Marseille · disembark 9 AM",
      ],
    },

    tours: [
      { date: "Wed May 27", name: "Savour Sultry Seville on Foot", operator: "MSC excursion · code CAD11", confirmation: "Booked on cruise card" },
      { date: "Thu May 28", name: "Pastel de Nata Masterclass", operator: "Nat'elier · Rua de Santa Justa 87, Lisbon · 10 AM, 2 hrs · arrive 9:50", confirmation: "NATA-T128887747 · €140 prepaid" },
      { date: "Sat May 30", name: "Spanish Castle Magic in Guadalest", operator: "MSC excursion · code ALI11 · 4.5 hrs", confirmation: "Booked on cruise card" },
      { date: "Mon Jun 1", name: "Exploring the La Maddalena Archipelago", operator: "MSC excursion · code OLB01", confirmation: "Booked on cruise card" },
      { date: "Thu Jun 4", name: "Normandy / D-Day + Mont Saint-Michel", operator: "Amigo Tours · meet 7 AM at 11 Bd Pershing (Hyatt Regency Etoile)", confirmation: "GYGBLHQALLK3 · Mont St-Michel abbey tix included" },
    ],

    parking: {
      where: "DFW Terminal A garage",
      confirmation: "DFWTA-1332579",
      lpn: "XV1751 (auto-gate via license plate · call button if it doesn't read)",
      start: "Sun May 24, 9:00 AM",
      end: "Fri Jun 5, 3:00 PM",
      total: "$342.50 · Mastercard ending 2060",
      note: "Park at A (skip Terminal C construction). Check in / bag drop at AA Terminal A. Skylink to gate C. On return: land Terminal D → TerminaLink shuttle (free, landside) to A garage.",
    },

    contacts: [
      { who: "The Highland Dallas", phone: "+1 214-520-7969" },
      { who: "Casablanca Marriott", phone: "+212 522-43-94-94" },
      { who: "Le Méridien Paris Étoile", phone: "+33 1 40 68 34 34" },
      { who: "MSC Cruises Customer Service (US)", phone: "+1 877-665-4655" },
      { who: "Amigo Tours (Normandy)", phone: "+34 911 293 483" },
      { who: "Marriott International", phone: "+1 800-228-9290" },
      { who: "American Airlines", phone: "+1 800-433-7300" },
      { who: "Air France (US)", phone: "+1 800-237-2747" },
      { who: "Royal Air Maroc (US)", phone: "+1 800-344-6726" },
      { who: "US State Dept · emergencies abroad", phone: "+1 202-501-4444" },
    ],

    notes: "Sat May 23: drive to Dallas, dinner at Culver's, check in to Highland, sack lunches for the kids' camp trip. Sun May 24: out of Highland early, drop the kids at Lake Highlands High for the camp bus, DFW Terminal A garage by ~9 AM, TerminaLink bus to Terminal C for AA check-in + bag drop + security, then to the gate for 11:57 AM departure. Casablanca arrival May 25: taxi from RAM official stand (~$25–30, 30 min) to Marriott; front desk will hold bags pre-3-PM. Cruise check-in deadline May 26 is 4 PM Málaga local — landing 13:20 leaves about 1h 45m buffer. Time zones: Morocco & Portugal +6 from Midland, everywhere else +7.",
  },
};
