// ============================================================
// SHAFFER EUROPE 2026 — content file
// This is the ONLY file you normally need to edit.
// Add a photo: drop into images/, then list it in the day's `photos`.
// Add an audio postcard: drop into audio/, then set `audio` on the day.
// ============================================================

window.TRIP = {
  meta: {
    title: "Shaffers Abroad",
    tagline: "Fifteen days across Morocco, the Mediterranean, and France",
    departDate: "2026-05-22",  // first travel day
    sailDate: "2026-05-25",
    returnDate: "2026-06-05",
    travelers: "Jason & Rachel",
    hashtag: "ShaffersAbroad26",
  },

  // The whole trip, day by day. Edit freely.
  days: [
    {
      id: "day-1",
      date: "2026-05-22",
      label: "Day 1 · Fri",
      city: "Midland → Dallas",
      country: "TX",
      flag: "🇺🇸",
      kicker: "Travel day",
      title: "Heading east, slow start.",
      summary: "Drive (or short hop) to Dallas. One last Texas night before the long flight.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-2",
      date: "2026-05-23",
      label: "Day 2 · Sat",
      city: "Dallas → Casablanca",
      country: "Morocco",
      flag: "🇲🇦",
      kicker: "The overnight flight",
      title: "Wheels up to Africa.",
      summary: "DFW to Casablanca. Movie-marathon altitude. Arrival the next morning.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-3",
      date: "2026-05-24",
      label: "Day 3 · Sun",
      city: "Casablanca",
      country: "Morocco",
      flag: "🇲🇦",
      kicker: "Land in Morocco",
      title: "Hassan II Mosque, the corniche, mint tea.",
      summary: "Arrive Casablanca. Check in at the Marriott. A first walk along the Atlantic, the Hassan II Mosque at golden hour.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-4",
      date: "2026-05-25",
      label: "Day 4 · Mon",
      city: "Casablanca → Málaga",
      country: "Spain · 🇪🇸",
      flag: "🇪🇸",
      kicker: "Board the ship",
      title: "Crossing to Spain — embark the MSC Opera.",
      summary: "Fly Casablanca to Málaga. Board the MSC Opera that evening for an eight-night Mediterranean run.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-5",
      date: "2026-05-26",
      label: "Day 5 · Tue",
      city: "Cádiz",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 1",
      title: "Cádiz — Europe's oldest city.",
      summary: "First port. Whitewashed lanes, tapas in the plaza, the cathedral over the sea.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-6",
      date: "2026-05-27",
      label: "Day 6 · Wed",
      city: "Lisbon",
      country: "Portugal",
      flag: "🇵🇹",
      kicker: "Cruise · Port 2",
      title: "Lisbon — and maybe a day up the hill to Sintra.",
      summary: "Yellow trams, pastéis de nata, the river. Sintra's palaces in fairy-tale mist sit 45 minutes up the hill if we go for it.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-7",
      date: "2026-05-28",
      label: "Day 7 · Thu",
      city: "Sea day",
      country: "Atlantic → Mediterranean",
      flag: "🌊",
      kicker: "Cruise · At sea",
      title: "A day for the deck chairs.",
      summary: "Heading east into the Med. Books, coffee, sun, repeat.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-8",
      date: "2026-05-29",
      label: "Day 8 · Fri",
      city: "Alicante",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 3",
      title: "Alicante — the Costa Blanca.",
      summary: "A harbor town under a hilltop castle. Esplanade palms, seafood paella, the sea everywhere.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-9",
      date: "2026-05-30",
      label: "Day 9 · Sat",
      city: "Menorca (Mahón)",
      country: "Spain · Balearics",
      flag: "🇪🇸",
      kicker: "Cruise · Port 4",
      title: "Menorca — the quiet Balearic.",
      summary: "Quieter sister to Mallorca and Ibiza. Pale-blue coves, a deep natural harbor, gin and lemonade in the shade.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-10",
      date: "2026-05-31",
      label: "Day 10 · Sun",
      city: "Sardinia (Cagliari)",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 5",
      title: "Cagliari — Sardinia's old capital.",
      summary: "A castle-topped old town over a turquoise gulf. Pasta with bottarga and a long walk on the marina.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-11",
      date: "2026-06-01",
      label: "Day 11 · Mon",
      city: "Genoa",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 6",
      title: "Genoa — the old maritime republic.",
      summary: "Narrow medieval lanes, painted palazzos, the smell of focaccia in the air. The Italian Riviera at our backs.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-12",
      date: "2026-06-02",
      label: "Day 12 · Tue",
      city: "Sea day → Marseille",
      country: "France",
      flag: "🇫🇷",
      kicker: "Cruise · At sea",
      title: "Last day at sea.",
      summary: "Pack the bags. One more dinner on the ship. Marseille on the horizon.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-13",
      date: "2026-06-03",
      label: "Day 13 · Wed",
      city: "Marseille → Paris",
      country: "France",
      flag: "🇫🇷",
      kicker: "Off the ship · Onward",
      title: "Disembark. Train to Paris.",
      summary: "Off the MSC Opera at Marseille. Onward to Paris and the Le Méridien Arc de Triomphe.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-14",
      date: "2026-06-04",
      label: "Day 14 · Thu",
      city: "Normandy",
      country: "France",
      flag: "🇫🇷",
      kicker: "Day trip",
      title: "D-Day beaches and Mont Saint-Michel.",
      summary: "Full-day private tour out of Paris — Omaha Beach, the American Cemetery, then the impossible silhouette of Mont Saint-Michel rising from the bay.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-15",
      date: "2026-06-05",
      label: "Day 15 · Fri",
      city: "Paris → Home",
      country: "USA",
      flag: "🇺🇸",
      kicker: "Travel day",
      title: "Home to Texas.",
      summary: "One last espresso in Paris. Fly to DFW. Land tired, full, and happy.",
      photos: [],
      audio: null,
      journal: "",
    },
  ],

  // Country/stop strip at the top
  cities: [
    { name: "Casablanca", flag: "🇲🇦" },
    { name: "Málaga", flag: "🇪🇸" },
    { name: "Cádiz", flag: "🇪🇸" },
    { name: "Lisbon", flag: "🇵🇹" },
    { name: "Alicante", flag: "🇪🇸" },
    { name: "Menorca", flag: "🇪🇸" },
    { name: "Sardinia", flag: "🇮🇹" },
    { name: "Genoa", flag: "🇮🇹" },
    { name: "Marseille", flag: "🇫🇷" },
    { name: "Paris", flag: "🇫🇷" },
    { name: "Normandy", flag: "🇫🇷" },
  ],

  // "Where are they now" — update this single object as the trip progresses.
  whereNow: {
    city: "Midland, TX",
    country: "Pre-trip",
    note: "Bags by the door. Final check.",
    updated: "2026-05-22",
  },

  // ============================================================
  // PRIVATE — gated behind the password on private.html.
  // ============================================================
  private: {
    flights: [
      { date: "2026-05-23", route: "DFW → CMN", airline: "(see Amex Travel app)", confirmation: "(in itinerary email)" },
      { date: "2026-05-25", route: "CMN → AGP", airline: "(see Amex Travel app)", confirmation: "(in itinerary email)" },
      { date: "2026-06-03", route: "MRS → CDG", airline: "(see Amex Travel app)", confirmation: "(in itinerary email)" },
      { date: "2026-06-05", route: "CDG → DFW", airline: "(see Amex Travel app)", confirmation: "(in itinerary email)" },
    ],
    hotels: [
      {
        date: "2026-05-23 → 2026-05-25",
        name: "Casablanca Marriott",
        city: "Casablanca, Morocco",
        confirmation: "(check email)",
      },
      {
        date: "2026-06-03 → 2026-06-05",
        name: "Le Méridien Étoile (Arc de Triomphe)",
        city: "Paris, France",
        confirmation: "(check email)",
      },
    ],
    cruise: {
      ship: "MSC Opera",
      booking: "71516081",
      checkIn: "Completed online 2026-04-19",
      boardDate: "2026-05-25 (Málaga)",
      disembarkDate: "2026-06-03 (Marseille)",
      duration: "8 nights",
      stateroom: "(see MSC confirmation email)",
      diningTime: "(see MSC confirmation email)",
    },
    tours: [
      { date: "2026-06-04", name: "Normandy + Mont Saint-Michel private day tour", operator: "(see booking email)", confirmation: "(see booking email)" },
    ],
    contacts: [
      { who: "MSC Cruises Customer Service", phone: "1 (877) 665-4655" },
      { who: "Marriott International", phone: "1 (800) 228-9290" },
      { who: "Le Méridien Étoile (Paris)", phone: "+33 1 40 68 34 34" },
      { who: "US State Dept emergencies abroad", phone: "+1 202-501-4444" },
    ],
    notes: "Add anything here you want quick access to — wifi passwords, photocopy of passport links, parking details, rental car PINs.",
  },
};
