// ============================================================
// SHAFFERS ABROAD — content file (single source of truth on the site)
// Mirrors the master dossier in iCloud Drive (trip-dossier.md).
// Edit here, then commit + push.
// ============================================================

window.TRIP = {
  meta: {
    title: "Shaffers Abroad",
    tagline: "Two weeks across Morocco, the Mediterranean, and France",
    departDate: "2026-05-23",  // drive to Dallas (pre-trip night)
    sailDate: "2026-05-26",
    returnDate: "2026-06-05",
    travelers: "Jason & Rachel",
    hashtag: "ShaffersAbroad26",
  },

  // Day by day. Day 0 is the pre-trip Dallas overnight.
  days: [
    {
      id: "day-0",
      date: "2026-05-23",
      label: "Sat May 23 · Night before",
      city: "Dallas, TX",
      country: "USA",
      flag: "🇺🇸",
      kicker: "Pre-trip overnight",
      title: "One night at The Highland.",
      summary: "Drop the kids, drive to Dallas, dinner at Knife on-site. Bags packed, sleep close to DFW.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-1",
      date: "2026-05-24",
      label: "Day 1 · Sun May 24",
      city: "DFW → JFK → Casablanca",
      country: "🇺🇸 → 🇲🇦",
      flag: "✈️",
      kicker: "Travel day · the long one",
      title: "Wheels up, three planes, one ocean.",
      summary: "Drop the kids in Lake Highlands. Park at DFW Terminal A. AA to JFK at 11:57 AM, then the overnight Royal Air Maroc 787 to Casablanca.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-2",
      date: "2026-05-25",
      label: "Day 2 · Mon May 25",
      city: "Casablanca",
      country: "Morocco",
      flag: "🇲🇦",
      kicker: "Land in Africa",
      title: "Mint tea in the Habous Quarter.",
      summary: "Arrive 8:50 AM. Nap at the Marriott, then a self-guided afternoon in the Habous Quarter — leather, lanterns, spices, a slow tea, dinner back at the hotel. Eid al-Adha is two days off, so the city feels busy and warm.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-3",
      date: "2026-05-26",
      label: "Day 3 · Tue May 26",
      city: "Casablanca → Málaga · Embark",
      country: "Morocco → Spain",
      flag: "🛳",
      kicker: "Board the MSC Opera",
      title: "Crossing to Spain — boarding day.",
      summary: "Morning Royal Air Maroc to Málaga. Taxi to the cruise terminal. Onboard the MSC Opera by 4 PM, sailing 6 PM. Eight nights, six ports.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-4",
      date: "2026-05-27",
      label: "Day 4 · Wed May 27",
      city: "Cádiz · Seville",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 1",
      title: "Savoury Seville on foot.",
      summary: "Dock in Cádiz 7 AM. MSC excursion takes us to Seville for a walking tour — cathedral, orange-tree courtyards, the old Jewish quarter. Back onboard by 5 PM.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-5",
      date: "2026-05-28",
      label: "Day 5 · Thu May 28",
      city: "Lisbon",
      country: "Portugal",
      flag: "🇵🇹",
      kicker: "Cruise · Port 2",
      title: "Pastel de nata, then the city on foot.",
      summary: "Morning pastel-de-nata masterclass at Nat'elier (10 AM). Afternoon walk down through Santa Justa Lift, the Carmo Convent, Time Out Market for lunch, the river at Praça do Comércio.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-6",
      date: "2026-05-29",
      label: "Day 6 · Fri May 29",
      city: "At Sea",
      country: "Mediterranean",
      flag: "🌊",
      kicker: "Cruise · Sea day",
      title: "A day for the deck chairs.",
      summary: "Heading east into the Med. Books, coffee, sun, an espresso, a long lunch. Repeat.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-7",
      date: "2026-05-30",
      label: "Day 7 · Sat May 30",
      city: "Alicante · Guadalest",
      country: "Spain",
      flag: "🇪🇸",
      kicker: "Cruise · Port 3",
      title: "Spanish castle magic in the mountains.",
      summary: "Dock 9 AM. Bus up into the Costa Blanca hills to Guadalest, a tiny clifftop village in a Moorish castle. Back by mid-afternoon.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-8",
      date: "2026-05-31",
      label: "Day 8 · Sun May 31",
      city: "Mahón, Menorca",
      country: "Spain · Balearics",
      flag: "🇪🇸",
      kicker: "Cruise · Port 4 · Free day",
      title: "The quiet Balearic.",
      summary: "Quieter sister to Mallorca and Ibiza. Mahón has one of the deepest natural harbors in the world. A wander, a long lunch, gin and lemonade on a terrace.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-9",
      date: "2026-06-01",
      label: "Day 9 · Mon Jun 1",
      city: "Olbia, Sardinia · La Maddalena",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 5",
      title: "Boating the La Maddalena Archipelago.",
      summary: "Dock 10 AM. Out on the water through the granite islands of La Maddalena — pale-turquoise coves, beach stops, the kind of color that doesn't photograph right.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-10",
      date: "2026-06-02",
      label: "Day 10 · Tue Jun 2",
      city: "Genoa",
      country: "Italy",
      flag: "🇮🇹",
      kicker: "Cruise · Port 6 · Free day",
      title: "The old maritime republic.",
      summary: "Narrow medieval lanes, painted palazzos, the smell of focaccia. The birthplace of Columbus and pesto. The Italian Riviera at our backs.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-11",
      date: "2026-06-03",
      label: "Day 11 · Wed Jun 3",
      city: "Marseille → Paris",
      country: "France",
      flag: "🇫🇷",
      kicker: "Disembark · Onward",
      title: "Off the ship and on to Paris.",
      summary: "Disembark Marseille 9 AM. Afternoon flight to Paris. Check in at Le Méridien Arc de Triomphe, dinner, sleep.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-12",
      date: "2026-06-04",
      label: "Day 12 · Thu Jun 4",
      city: "Normandy + Mont Saint-Michel",
      country: "France",
      flag: "🇫🇷",
      kicker: "Day trip · 7 AM start",
      title: "D-Day beaches and a fortress on the bay.",
      summary: "Full-day Amigo Tours private trip — Omaha Beach, the American Cemetery, then the impossible silhouette of Mont Saint-Michel rising from the tide.",
      photos: [],
      audio: null,
      journal: "",
    },
    {
      id: "day-13",
      date: "2026-06-05",
      label: "Day 13 · Fri Jun 5",
      city: "Paris → Home",
      country: "France → USA",
      flag: "🇺🇸",
      kicker: "Travel day",
      title: "Home to Texas.",
      summary: "One last espresso. AA 49 nonstop Paris → DFW, lands 1:30 PM. Tired, full, and happy.",
      photos: [],
      audio: null,
      journal: "",
    },
  ],

  cities: [
    { name: "Dallas", flag: "🇺🇸" },
    { name: "Casablanca", flag: "🇲🇦" },
    { name: "Málaga", flag: "🇪🇸" },
    { name: "Cádiz · Seville", flag: "🇪🇸" },
    { name: "Lisbon", flag: "🇵🇹" },
    { name: "Alicante", flag: "🇪🇸" },
    { name: "Mahón", flag: "🇪🇸" },
    { name: "Olbia · Sardinia", flag: "🇮🇹" },
    { name: "Genoa", flag: "🇮🇹" },
    { name: "Marseille", flag: "🇫🇷" },
    { name: "Paris", flag: "🇫🇷" },
    { name: "Normandy", flag: "🇫🇷" },
  ],

  whereNow: {
    city: "Midland, TX",
    country: "Pre-trip · home",
    note: "Bags by the door. Final check.",
    updated: "2026-05-22",
  },

  // ============================================================
  // PRIVATE — behind the password on /private.html.
  // ============================================================
  private: {
    flights: [
      {
        date: "Sun May 24",
        route: "DFW (Term C) → JFK (Term 8)",
        airline: "American AA 1049 · Airbus A321",
        times: "11:57 AM → 4:38 PM",
        seats: "Jason 14F · Rachel 14E (Economy L)",
        confirmation: "ECWYBK",
      },
      {
        date: "Sun May 24",
        route: "JFK → CMN (Casablanca)",
        airline: "American AA 7951 / Royal Air Maroc · Boeing 787-9",
        times: "8:45 PM → 8:50 AM May 25 (overnight)",
        seats: "Economy L",
        confirmation: "CW9X3L (RAM) · ECWYBK (AA)",
      },
      {
        date: "Tue May 26",
        route: "CMN (Term 1) → AGP (Málaga)",
        airline: "Royal Air Maroc AT 988 · 737 MAX 8",
        times: "11:05 → 13:20 (1h 15m)",
        seats: "Jason 9B · Rachel 9A",
        confirmation: "Y7JINE · eTickets: J 1472426730054, R 1472426730055",
      },
      {
        date: "Wed Jun 3",
        route: "MRS (Term 1) → CDG (Term 2F)",
        airline: "Air France AF 7339",
        times: "15:05 → 16:35 (1h 30m)",
        seats: "Jason 6B · Rachel 6A",
        confirmation: "YJPQJY · check-in deadline 14:35",
      },
      {
        date: "Fri Jun 5",
        route: "CDG → DFW",
        airline: "American AA 49 · Boeing 787-9",
        times: "10:00 AM → 1:30 PM",
        seats: "29D · 29E (Economy O)",
        confirmation: "ECWYBK (round-trip ref)",
      },
    ],

    hotels: [
      {
        date: "May 23 (1 night) · Pre-trip",
        name: "The Highland Dallas (Curio / Hilton)",
        city: "5300 E Mockingbird Ln, Dallas TX 75206",
        phone: "+1 214-520-7969",
        confirmation: "3482144721",
        notes: "1 King Luxury · check-in 3 PM · check-out 12 PM · Hilton Honors #552163196 · valet $55/night",
      },
      {
        date: "May 25 (1 night)",
        name: "Casablanca Marriott Hotel",
        city: "100 Avenue des FAR, Casablanca 20000",
        phone: "+212-522-439494",
        confirmation: "74156980",
        notes: "Superior King, city view · check-in 3 PM, check-out 12 PM · prepaid · Bonvoy Platinum · ⚠ confirm Rachel is on the booking (shows '1 Adult')",
      },
      {
        date: "Jun 3–4 (2 nights)",
        name: "Le Méridien Paris Arc de Triomphe",
        city: "81 Bd Gouvion Saint-Cyr, Paris 75017",
        phone: "+33-1-40683434",
        confirmation: "84262397",
        notes: "Executive King · check-in 4 PM, check-out 12 PM · prepaid · Bonvoy Platinum · refurbishment underway (full service)",
      },
    ],

    cruise: {
      ship: "MSC Opera",
      booking: "71516081",
      checkIn: "Completed (eTicket received Apr 25)",
      boardDate: "Tue May 26 · Málaga Cruise Terminal (Dique de Levante) · board 12–4 PM, sail 6 PM",
      disembarkDate: "Wed Jun 3 · Marseille · 9 AM",
      duration: "8 nights · 6 ports",
      stateroom: "Cabin 8208 · Deck 8 · Outside (window) · Fantastica",
      diningTime: "First Seating (table assigned on board)",
      assembly: "Station J",
      guestIds: "Jason 182730562 · Rachel 182730563",
      wifi: "Browse Wi-Fi package, 2 devices on Jason's account · network: MSCHOTSPOT",
      app: "MSC for Me · log in with booking #71516081",
      portTimes: [
        "Tue May 26 · Málaga · embark 12–4 PM, sail 6 PM",
        "Wed May 27 · Cádiz · 7 AM – 5 PM",
        "Thu May 28 · Lisbon · 9 AM – 6 PM",
        "Fri May 29 · At Sea",
        "Sat May 30 · Alicante · 9 AM – 5 PM",
        "Sun May 31 · Mahón, Menorca · 9 AM – 4 PM",
        "Mon Jun 1 · Olbia, Sardinia · 10 AM – 7 PM",
        "Tue Jun 2 · Genoa · 9 AM – 6 PM",
        "Wed Jun 3 · Marseille · disembark 9 AM",
      ],
    },

    tours: [
      { date: "Wed May 27", name: "Savour Sultry Seville on Foot", operator: "MSC excursion · code CAD11", confirmation: "Booked on cruise card" },
      { date: "Thu May 28", name: "Pastel de Nata Masterclass", operator: "Nat'elier · Rua de Santa Justa 87, Lisbon · 10 AM, 2 hrs · arrive 9:50", confirmation: "NATA-T128887747 · €140 prepaid" },
      { date: "Sat May 30", name: "Spanish Castle Magic in Guadalest", operator: "MSC excursion · code ALI11 · 4.5 hrs", confirmation: "Booked on cruise card" },
      { date: "Mon Jun 1", name: "Exploring the La Maddalena Archipelago", operator: "MSC excursion · code OLB01", confirmation: "Booked on cruise card" },
      { date: "Thu Jun 4", name: "Normandy / D-Day + Mont Saint-Michel", operator: "Amigo Tours · meet 7 AM at 11 Bd Pershing (Hyatt Regency Etoile)", confirmation: "GYGBLHQALLK3 · Mont St-Michel abbey tix included" },
    ],

    parking: {
      where: "DFW Terminal A garage",
      confirmation: "DFWTA-1332579",
      lpn: "XV1751 (auto-gate via license plate · call button if it doesn't read)",
      start: "Sun May 24, 9:00 AM",
      end: "Fri Jun 5, 3:00 PM",
      total: "$342.50 · Mastercard ending 2060",
      note: "Park at A (skip Terminal C construction). Check in / bag drop at AA Terminal A. Skylink to gate C. On return: land Terminal D → TerminaLink shuttle (free, landside) to A garage.",
    },

    contacts: [
      { who: "The Highland Dallas", phone: "+1 214-520-7969" },
      { who: "Casablanca Marriott", phone: "+212 522-43-94-94" },
      { who: "Le Méridien Paris Étoile", phone: "+33 1 40 68 34 34" },
      { who: "MSC Cruises Customer Service (US)", phone: "+1 877-665-4655" },
      { who: "Amigo Tours (Normandy)", phone: "+34 911 293 483" },
      { who: "Marriott International", phone: "+1 800-228-9290" },
      { who: "American Airlines", phone: "+1 800-433-7300" },
      { who: "Air France (US)", phone: "+1 800-237-2747" },
      { who: "Royal Air Maroc (US)", phone: "+1 800-344-6726" },
      { who: "US State Dept · emergencies abroad", phone: "+1 202-501-4444" },
    ],

    notes: "Sunday May 24 plan: out of Highland by 9 AM, drop kids at LHHS, DFW Terminal A garage by 9 AM-ish, AA Terminal A counter for bag drop + security, Skylink to gate C. Casablanca arrival May 25: taxi from RAM official stand (~$25–30, 30 min) to Marriott; ask front desk to hold bags pre-3-PM. Cruise check-in deadline May 26 is 4 PM Málaga local — landing 13:20 leaves about 1h 45m buffer. Time zones: Morocco & Portugal +6 from Midland, everywhere else +7.",
  },
};
